/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.OpenProblem.New.Complexity.WordRAM.Machine
import Mathlib.Data.Real.Basic



section

/-!
# Polynomial time for bounded Word-RAM

`executionCost` is the cost of a correct machine execution. `HasCostBound` bounds this
cost pointwise. `IsPolynomialTime` requires an eventual polynomial bound in the fixed
input encoding's bit capacity. The coefficient, exponent, and threshold are chosen
uniformly before the input.
-/

namespace EconCSLib.OpenProblem.New.WordRAM.StrictCostCore

universe u v

noncomputable section

/-- The exact cost generated by the fixed Word-RAM interpreter. -/
def executionCost
    {Input : Type u} {Output : Input → Type v}
    {model : Model}
    {inputEncoding : Encoding Input}
    {outputEncoding : DependentEncoding Output}
    {function : (input : Input) → Output input}
    (implementation :
      WordRAM.Implementation model inputEncoding outputEncoding function)
    (input : Input) : ℕ :=
  WordRAM.Implementation.operationCount implementation input

/-- A user-supplied function is a sound pointwise upper bound for the actual interpreter
cost. It need not be the exact cost. -/
def HasCostBound
    {Input : Type u} {Output : Input → Type v}
    {model : Model}
    {inputEncoding : Encoding Input}
    {outputEncoding : DependentEncoding Output}
    {function : (input : Input) → Output input}
    (implementation :
      WordRAM.Implementation model inputEncoding outputEncoding function)
    (bound : Input → ℕ) : Prop :=
  ∀ input, executionCost implementation input ≤ bound input

/-- `cost` is eventually bounded by one real-coefficient polynomial normal form in `size`.
The coefficient, exponent, and finite-prefix threshold are existential because this
core records only membership in polynomial time.

For finitely many nonnegative input parameters, their sum may be supplied as `size`;
this is equivalent for polynomial boundedness to using a multivariate polynomial. -/
def IsEventuallyBoundedByPolynomial
    {Input : Type u} (size : Input → ℕ) (cost : Input → ℕ) : Prop :=
  ∃ coefficient : ℝ, 0 ≤ coefficient ∧
    ∃ exponent threshold : ℕ, ∀ input,
      threshold ≤ size input →
        (cost input : ℝ) ≤
          coefficient * (1 + (size input : ℝ)) ^ exponent

/-- Polynomial-time execution in the total bit length of the canonical packed input,
according to the bounded Word-RAM fixed by `model`. This is the only final complexity
classification in the mini core. -/
def IsPolynomialTime
    {Input : Type u} {Output : Input → Type v}
    {model : Model}
    {inputEncoding : Encoding Input}
    {outputEncoding : DependentEncoding Output}
    {function : (input : Input) → Output input}
    (implementation :
      WordRAM.Implementation model inputEncoding outputEncoding function) :
    Prop :=
  IsEventuallyBoundedByPolynomial
    (inputEncoding.bitSize model)
    (executionCost implementation)

end

end EconCSLib.OpenProblem.New.WordRAM.StrictCostCore

end
