/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.OpenProblem.New.SharedConcepts.All
import EconCSLib.OpenProblem.New.Complexity.All
import EconCSLib.OpenProblem.Util.Answer
import Mathlib.Data.Fintype.Perm
import Mathlib.MeasureTheory.Integral.Lebesgue.Basic
import Mathlib.Probability.Independence.Basic

/-!
# 17. Prophet inequalities for subadditive combinatorial auctions
-/



section

/-!
## Static pricing for subadditive combinatorial auctions

The literal Markdown valuation assumptions and the normalized monotone reference
convention [DKL, Section 2] are separate. Prices are nonnegative, anonymous, and
static. The benchmark uses complete partitions. Nonnegative extended expectations
avoid an unstated finite-mean restriction. There is no runtime or query bound.
-/
open scoped BigOperators ENNReal

namespace EconCSLib.OpenProblem.New.EconCSBench.SubadditiveStaticPricing

open MeasureTheory ProbabilityTheory
noncomputable section

/-- Literal nonnegative subadditivity versus the normalized monotone reference domain. -/
inductive ValuationConvention
  | asWritten
  | normalizedMonotone
  deriving DecidableEq

/-- A subset of the labeled item set; there is one copy of each item. -/
abbrev ItemBundle (items : ℕ) :=
  BundleAllocation (Finset.univ : Finset (Fin items))

/-- View any finite item set as an instance bundle. -/
def itemBundle {items : ℕ} (S : Finset (Fin items)) : ItemBundle items :=
  ⟨S, Finset.subset_univ S⟩

/-- Only the reference convention requires normalization and monotonicity. -/
def RespectsValuationConvention {items : ℕ} (mode : ValuationConvention)
    (value : ItemBundle items → ℝ) : Prop :=
  match mode with
  | .asWritten => True
  | .normalizedMonotone =>
      value (itemBundle ∅) = 0 ∧
        ∀ S T : ItemBundle items, S.val ⊆ T.val → value S ≤ value T

/-- The literal domain need not be normalized, unlike the shared subadditive valuation
type. Correlations between bundles are unrestricted. -/
structure BuyerValuation (mode : ValuationConvention) (items : ℕ) where
  val : ItemBundle items → ℝ
  nonnegative : ∀ S, 0 ≤ val S
  subadditive : ∀ S T : ItemBundle items,
    val (itemBundle (S.val ∪ T.val)) ≤ val S + val T
  convention : RespectsValuationConvention mode val

/-- The measurable structure generated by all bundle-value coordinates. -/
instance {mode : ValuationConvention} {items : ℕ} :
    MeasurableSpace (BuyerValuation mode items) :=
  MeasurableSpace.comap (fun v : BuyerValuation mode items => v.val) inferInstance

/-- The realized profile is unknown when prices are selected. -/
abbrev ValuationProfile (mode : ValuationConvention) (buyers items : ℕ) :=
  Fin buyers → BuyerValuation mode items

/-- A single price per item, independent of buyer, time, and inventory. -/
abbrev ItemPrices (items : ℕ) :=
  BundlePriceVector (Finset.univ : Finset (Fin items))

/-- Disjoint allocated bundles; items may remain unsold. -/
abbrev PricingAllocation (buyers items : ℕ) :=
  BundlePartitionAllocation (Fin buyers) (Finset.univ : Finset (Fin items))

/-- The finite outcome space has its discrete measurable structure. -/
local instance {buyers items : ℕ} : MeasurableSpace (PricingAllocation buyers items) := ⊤

/-- Social welfare, not revenue or utility net of payments. -/
def pricingWelfare {mode : ValuationConvention} {buyers items : ℕ}
    (v : ValuationProfile mode buyers items) (A : PricingAllocation buyers items) : ℝ :=
  bundleSocialWelfare (fun i => (v i).val) A

/-- An owner function encodes a complete benchmark partition. -/
def ownerBundle {buyers items : ℕ} (owner : Fin items → Fin buyers)
    (i : Fin buyers) : ItemBundle items :=
  itemBundle (Finset.univ.filter fun g => owner g = i)

/-- The nonnegative supremum over all complete partitions; OPT is not an oracle provided
to the mechanism. -/
def completeOPT {mode : ValuationConvention} {buyers items : ℕ}
    (v : ValuationProfile mode buyers items) : ℝ≥0∞ :=
  ⨆ owner : Fin items → Fin buyers,
    ENNReal.ofReal (∑ i, (v i).val (ownerBundle owner i))

/-- Independent buyer priors; no identical-distribution, density, or finite-support
assumption. -/
structure BayesianSubadditiveInstance
    (mode : ValuationConvention) (buyers items : ℕ) where
  prior : Measure (ValuationProfile mode buyers items)
  probability : IsProbabilityMeasure prior
  independent : iIndepFun
    (fun i (v : ValuationProfile mode buyers items) => v i) prior

/-- Expected pointwise OPT, permitting an infinite expectation. -/
def expectedSubadditiveOPT {mode : ValuationConvention} {buyers items : ℕ}
    (problem : BayesianSubadditiveInstance mode buyers items) : ℝ≥0∞ :=
  ∫⁻ v, completeOPT v ∂problem.prior

/-- Items remaining before position `t`, subtracting only earlier allocations. -/
def remainingItems {buyers items : ℕ} (A : PricingAllocation buyers items)
    (order : Equiv.Perm (Fin buyers)) (t : Fin buyers) : Finset (Fin items) :=
  Finset.univ \ (Finset.univ.filter (fun s : Fin buyers => s < t)).biUnion
    (fun s => (A.val (order s)).val)

/-- Every buyer chooses a utility-maximizing remaining bundle, including the empty bundle. -/
def IsStaticSubadditiveOutcome {mode : ValuationConvention} {buyers items : ℕ}
    (price : ItemPrices items) (v : ValuationProfile mode buyers items)
    (order : Equiv.Perm (Fin buyers)) (A : PricingAllocation buyers items) : Prop :=
  ∀ t, IsDemandBundle (v (order t)).val price
    (remainingItems A order t) (A.val (order t))

/-- A measurable demand selection. Adversarial selections may see the full profile;
seller-chosen selections must satisfy `HasLocalResponse`. -/
structure StaticDemandRule {mode : ValuationConvention} {buyers items : ℕ}
    (price : ItemPrices items) where
  outcome : ValuationProfile mode buyers items → Equiv.Perm (Fin buyers) →
    PricingAllocation buyers items
  measurable : ∀ order, Measurable (fun v => outcome v order)
  demand : ∀ v order, IsStaticSubadditiveOutcome price v order (outcome v order)

/-- A deterministic response sees arrival position, identity, own value, and remaining
items only. -/
abbrev LocalResponse (mode : ValuationConvention) (buyers items : ℕ) :=
  Fin buyers → Fin buyers → BuyerValuation mode items →
    ItemBundle items → ItemBundle items

/-- The same local response works for all profiles and orders. -/
def HasLocalResponse {mode : ValuationConvention} {buyers items : ℕ}
    {price : ItemPrices items} (rule : StaticDemandRule (mode := mode) (buyers := buyers) price) : Prop :=
  ∃ response : LocalResponse mode buyers items, ∀ v order t,
    (rule.outcome v order).val (order t) =
      response t (order t) (v (order t))
        (itemBundle (remainingItems (rule.outcome v order) order t))

/-- Known indexed order, unknown order fixed before values, or value-aware order. -/
inductive ArrivalConvention
  | knownIndexed
  | unknownFixed
  | valueAware
  deriving DecidableEq

/-- A seller-chosen local rule versus every measurable demand selection. -/
inductive TieConvention
  | localChoice
  | robustDemand
  deriving DecidableEq

/-- Nonnegative expected welfare at a fixed arrival order. -/
def expectedSubadditiveWelfare {mode : ValuationConvention} {buyers items : ℕ}
    {price : ItemPrices items} (problem : BayesianSubadditiveInstance mode buyers items)
    (rule : StaticDemandRule (mode := mode) (buyers := buyers) price)
    (order : Equiv.Perm (Fin buyers)) : ℝ≥0∞ :=
  ∫⁻ v, ENNReal.ofReal (pricingWelfare v (rule.outcome v order)) ∂problem.prior

/-- For unknown fixed order, the order quantifier is outside expectation; for value-aware
order, the minimum is inside. -/
def MeetsFactor {mode : ValuationConvention} {buyers items : ℕ}
    {price : ItemPrices items} (arrival : ArrivalConvention) (C : ℝ)
    (problem : BayesianSubadditiveInstance mode buyers items)
    (rule : StaticDemandRule (mode := mode) (buyers := buyers) price) : Prop :=
  match arrival with
  | .knownIndexed =>
      expectedSubadditiveOPT problem ≤
        ENNReal.ofReal C * expectedSubadditiveWelfare problem rule (Equiv.refl _)
  | .unknownFixed =>
      ∀ order, expectedSubadditiveOPT problem ≤
        ENNReal.ofReal C * expectedSubadditiveWelfare problem rule order
  | .valueAware =>
      expectedSubadditiveOPT problem ≤ ENNReal.ofReal C *
        (∫⁻ v, (⨅ order : Equiv.Perm (Fin buyers),
          ENNReal.ofReal (pricingWelfare v (rule.outcome v order))) ∂problem.prior)

end
end EconCSLib.OpenProblem.New.EconCSBench.SubadditiveStaticPricing

end


section

/-!
## Constant-factor static pricing for subadditive valuations

The factor is uniform over all market sizes and independent priors. Prices are chosen
after the prior but before realized values. This is an existential question with no
computational restriction. The reference baseline uses normalized monotone values and
known indexed order; stronger order and tie requirements are stated separately.
-/
namespace EconCSLib.OpenProblem.New.EconCSBench.SubadditiveStaticPricing

noncomputable section

/-- Require an existing local measurable rule; robust guarantees then quantify over all
measurable demand selections. -/
def PriceGuarantee {mode : ValuationConvention} {buyers items : ℕ}
    (arrival : ArrivalConvention) (ties : TieConvention) (C : ℝ)
    (problem : BayesianSubadditiveInstance mode buyers items) (price : ItemPrices items) : Prop :=
  ∃ localRule : StaticDemandRule (mode := mode) (buyers := buyers) price,
    HasLocalResponse localRule ∧
      match ties with
      | .localChoice => MeetsFactor arrival C problem localRule
      | .robustDemand => ∀ rule : StaticDemandRule (mode := mode) (buyers := buyers) price,
          MeetsFactor arrival C problem rule

/-- A finite positive universal factor, without positive-OPT or finite-expectation
promises. Relabeling buyers identifies known order with indexed order. -/
def ConstantFactorSubadditiveStaticPricingStatement
    (mode : ValuationConvention) (arrival : ArrivalConvention) (ties : TieConvention) : Prop :=
  ∃ C : ℝ, 0 < C ∧
    ∀ buyers items : ℕ, 0 < buyers →
      ∀ problem : BayesianSubadditiveInstance mode buyers items,
        ∃ price : ItemPrices items, (∀ g, 0 ≤ price g) ∧
          PriceGuarantee arrival ties C problem price

/-- Baseline question under normalized monotone values and known arrival order. -/
def ReferenceConstantFactorStatement : Prop :=
  ConstantFactorSubadditiveStaticPricingStatement
    .normalizedMonotone .knownIndexed .localChoice

end
end EconCSLib.OpenProblem.New.EconCSBench.SubadditiveStaticPricing

end


/-!
## Questions and answers
-/

namespace EconCSLib.OpenProblem.New.EconCSBench.SubadditiveStaticPricing

/-- Existence of a universal constant factor, without an additional runtime requirement. -/
theorem prophetInequalitySubadditiveCA :
    answer(sorry) ↔ ReferenceConstantFactorStatement := by
  sorry

end EconCSLib.OpenProblem.New.EconCSBench.SubadditiveStaticPricing
