/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.OpenProblem.New.SharedConcepts.All
import EconCSLib.OpenProblem.New.Complexity.All
import EconCSLib.OpenProblem.Util.Answer
import Mathlib.Data.Fintype.Perm
import Mathlib.MeasureTheory.Integral.Lebesgue.Basic
import Mathlib.Probability.Independence.Basic

/-!
# 16. Posted pricing with multiple copies and XOS valuations
-/



section

/-!
## Static item pricing with multiple copies

The CDHW (2025), Sections 2.1–2.3 model allows one copy of each item type per buyer.
Buyers maximize utility, not gross welfare. Prices are fixed before values and arrival
order. Order and tie conventions remain explicit; this is an existential pricing
specification, with no computational restriction.
-/
open scoped BigOperators ENNReal

namespace EconCSLib.OpenProblem.New.EconCSBench.PostedPricingMultiUnitXOS

open MeasureTheory ProbabilityTheory
noncomputable section

/-- A bundle contains item types. -/
abbrev ItemBundle (items : ℕ) :=
  BundleAllocation (Finset.univ : Finset (Fin items))

/-- XOS values, with the measurable structure generated by bundle values. -/
abbrev BuyerValuation (items : ℕ) :=
  XOSBundleValuation (Finset.univ : Finset (Fin items))

/-- The full realized profile, unavailable when prices are chosen. -/
abbrev ValuationProfile (buyers items : ℕ) := Fin buyers → BuyerValuation items

/-- The same price applies to every copy of an item type. -/
abbrev ItemPrices (items : ℕ) :=
  BundlePriceVector (Finset.univ : Finset (Fin items))

/-- Each item type is assigned to at most its available number of buyers. -/
def RespectsSupply {buyers items : ℕ} (supply : Fin items → ℕ)
    (allocation : Fin buyers → ItemBundle items) : Prop :=
  ∀ g, (Finset.univ.filter fun i => g ∈ (allocation i).val).card ≤ supply g

/-- Feasible allocations; unsold copies are permitted. -/
abbrev SupplyBundleAllocation (buyers : ℕ) {items : ℕ} (supply : Fin items → ℕ) :=
  { allocation : Fin buyers → ItemBundle items // RespectsSupply supply allocation }

/-- The finite outcome space carries the discrete measurable structure. -/
instance {buyers items : ℕ} {supply : Fin items → ℕ} :
    MeasurableSpace (SupplyBundleAllocation buyers supply) := ⊤

/-- Social welfare excludes transfers. -/
def supplyBundleWelfare {buyers items : ℕ} {supply : Fin items → ℕ}
    (v : ValuationProfile buyers items) (A : SupplyBundleAllocation buyers supply) : ℝ :=
  ∑ i, (v i).val (A.val i)

/-- Pointwise hindsight optimum under realized supply constraints. -/
def supplyBundleOPT {buyers items : ℕ} (supply : Fin items → ℕ)
    (v : ValuationProfile buyers items) : ℝ :=
  ⨆ A : SupplyBundleAllocation buyers supply, supplyBundleWelfare v A

/-- Independent, not necessarily identical priors. Atoms, zero OPT, and infinite expected
OPT are allowed; extended expectations impose no finite-mean promise. -/
structure BayesianXOSInstance (buyers : ℕ) {items : ℕ} (supply : Fin items → ℕ) where
  prior : Measure (ValuationProfile buyers items)
  probability : IsProbabilityMeasure prior
  independent : iIndepFun (fun i (v : ValuationProfile buyers items) => v i) prior

/-- Expectation of the pointwise optimum, not optimization of expected fixed allocations. -/
def expectedXOSOPT {buyers items : ℕ} {supply : Fin items → ℕ}
    (problem : BayesianXOSInstance buyers supply) : ℝ≥0∞ :=
  ∫⁻ v, ENNReal.ofReal (supplyBundleOPT supply v) ∂problem.prior

/-- Remaining stock immediately before position `t`; `order t` is the arriving buyer. -/
def remainingInventory {buyers items : ℕ} (supply : Fin items → ℕ)
    (A : Fin buyers → ItemBundle items) (order : Equiv.Perm (Fin buyers))
    (t : Fin buyers) : Fin items → ℕ :=
  fun g => supply g -
    (Finset.univ.filter fun s : Fin buyers => s < t ∧ g ∈ (A (order s)).val).card

/-- An item is available exactly when at least one copy remains. -/
def availableItems {items : ℕ} (inventory : Fin items → ℕ) : Finset (Fin items) :=
  Finset.univ.filter fun g => 0 < inventory g

/-- Every buyer selects a utility-maximizing available bundle. This outcome relation alone
does not enforce online tie-breaking. -/
def IsStaticPostedPriceOutcome {buyers items : ℕ} {supply : Fin items → ℕ}
    (price : ItemPrices items) (v : ValuationProfile buyers items)
    (order : Equiv.Perm (Fin buyers)) (A : SupplyBundleAllocation buyers supply) : Prop :=
  ∀ t, IsDemandBundle (v (order t)).val price
    (availableItems (remainingInventory supply A.val order t)) (A.val (order t))

/-- A measurable demand selection at every profile and order. Seller-chosen selections
additionally require `HasLocalResponse`; unrestricted selections model adversarial
ties. -/
structure StaticDemandRule {buyers items : ℕ} (supply : Fin items → ℕ)
    (price : ItemPrices items) where
  outcome : ValuationProfile buyers items → Equiv.Perm (Fin buyers) →
    SupplyBundleAllocation buyers supply
  measurable : ∀ order, Measurable (fun v => outcome v order)
  demand : ∀ v order, IsStaticPostedPriceOutcome price v order (outcome v order)

/-- A deterministic response sees position, buyer identity, own valuation, and remaining
inventory only. -/
abbrev LocalResponse (buyers items : ℕ) :=
  Fin buyers → Fin buyers → BuyerValuation items →
    (Fin items → ℕ) → ItemBundle items

/-- One local response works for every future completion and order; the equations advance
in arrival order. -/
def HasLocalResponse {buyers items : ℕ} {supply : Fin items → ℕ}
    {price : ItemPrices items} (rule : StaticDemandRule (buyers := buyers) supply price) : Prop :=
  ∃ response : LocalResponse buyers items, ∀ v order t,
    (rule.outcome v order).val (order t) =
      response t (order t) (v (order t))
        (remainingInventory supply (rule.outcome v order).val order t)

/-- Known indexed order, or an adversary choosing order after seeing values [CDHW, Section
2.3]. -/
inductive ArrivalConvention
  | indexed
  | valueAware
  deriving DecidableEq

/-- A seller-chosen local rule, or a guarantee against all measurable demand selections. -/
inductive TieConvention
  | localChoice
  | robustDemand
  deriving DecidableEq

/-- For a value-aware adversary, the minimum over orders is inside the expectation. -/
def realizedWelfare {buyers items : ℕ} {supply : Fin items → ℕ}
    {price : ItemPrices items} (arrival : ArrivalConvention)
    (rule : StaticDemandRule (buyers := buyers) supply price) (v : ValuationProfile buyers items) : ℝ :=
  match arrival with
  | .indexed => supplyBundleWelfare v (rule.outcome v (Equiv.refl _))
  | .valueAware => ⨅ order, supplyBundleWelfare v (rule.outcome v order)

/-- A nonnegative extended-expectation ratio inequality, without dividing by OPT. -/
def MeetsRatio {buyers items : ℕ} {supply : Fin items → ℕ}
    {price : ItemPrices items} (arrival : ArrivalConvention) (ratio : ℝ)
    (problem : BayesianXOSInstance buyers supply)
    (rule : StaticDemandRule (buyers := buyers) supply price) : Prop :=
  ENNReal.ofReal ratio * expectedXOSOPT problem ≤
    ∫⁻ v, ENNReal.ofReal (realizedWelfare arrival rule v) ∂problem.prior

end
end EconCSLib.OpenProblem.New.EconCSBench.PostedPricingMultiUnitXOS

end


section

/-!
## Does the static-pricing ratio converge uniformly to one?

The supply threshold depends only on epsilon, not on buyers, item types, or priors.
Prices are selected from the instance before its values and order. The reference
convention uses a value-aware arrival adversary and a local tie rule fixed before
realization. Robust tie-breaking is a separate, stronger question.
-/
namespace EconCSLib.OpenProblem.New.EconCSBench.PostedPricingMultiUnitXOS

noncomputable section

/-- Require a local demand rule even in the robust branch, preventing vacuous guarantees. -/
def PriceGuarantee {buyers items : ℕ} {supply : Fin items → ℕ}
    (arrival : ArrivalConvention) (ties : TieConvention) (ratio : ℝ)
    (problem : BayesianXOSInstance buyers supply) (price : ItemPrices items) : Prop :=
  ∃ localRule : StaticDemandRule (buyers := buyers) supply price, HasLocalResponse localRule ∧
    match ties with
    | .localChoice => MeetsRatio arrival ratio problem localRule
    | .robustDemand => ∀ rule : StaticDemandRule (buyers := buyers) supply price,
        MeetsRatio arrival ratio problem rule

/-- Uniform convergence over every supply vector above the threshold, including nonuniform
supplies. -/
def StaticXOSPricingConvergesToOneStatement
    (arrival : ArrivalConvention) (ties : TieConvention) : Prop :=
  ∀ ε : ℝ, 0 < ε → ∃ K : ℕ, 0 < K ∧
    ∀ buyers items : ℕ, 0 < buyers →
      ∀ supply : Fin items → ℕ, (∀ g, K ≤ supply g) →
        ∀ problem : BayesianXOSInstance buyers supply,
          ∃ price : ItemPrices items, (∀ g, 0 ≤ price g) ∧
            PriceGuarantee arrival ties (1 - ε) problem price

/-- Reference question: value-aware arrival and a local tie rule fixed before values. -/
def ReferenceStaticXOSPricingStatement : Prop :=
  StaticXOSPricingConvergesToOneStatement .valueAware .localChoice

end
end EconCSLib.OpenProblem.New.EconCSBench.PostedPricingMultiUnitXOS

end


/-!
## Questions and answers
-/

namespace EconCSLib.OpenProblem.New.EconCSBench.PostedPricingMultiUnitXOS

/-- Static anonymous item-type prices under the stated arrival and demand conventions. -/
theorem postedPricingMultiUnitXOS :
    answer(sorry) ↔ ReferenceStaticXOSPricingStatement := by
  sorry

end EconCSLib.OpenProblem.New.EconCSBench.PostedPricingMultiUnitXOS
