/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.MechanismDesign.Auction.VCG
import EconCSLib.OpenProblem.SubmodularWelfareDemandOracle
import EconCSLib.SocialChoice.FairDivision.Indivisible.Instance
import Mathlib.MeasureTheory.Constructions.Pi

/-!
# Valuations, welfare, demand, and fairness

Subadditive and XOS valuations, complete bundle allocations, social welfare,
restricted demand, partial allocations, and approximate EFX. The definitions use
EconCSLib's bundle and allocation types. Each theorem supplies its valuation
assumptions, feasibility conditions, and approximation-factor range.
-/


open scoped BigOperators

namespace EconCSLib.OpenProblem.New.EconCSBench

/-!
## Subadditive and XOS valuations
-/

/-- A monotone bundle valuation satisfying subadditivity. -/
structure SubadditiveBundleValuation
    {G : Type*} [DecidableEq G] (M : Finset G)
    extends MonotoneBundleValuation M where
  /-- The value of a union is at most the sum of the separate values. -/
  subadditive :
    ∀ S T : BundleAllocation M,
      val ⟨S.1 ∪ T.1, by
        intro g hg
        simp only [Finset.mem_union] at hg
        exact hg.elim (fun h => S.2 h) (fun h => T.2 h)⟩ ≤ val S + val T

/-- A valuation equal to the pointwise maximum of finitely many nonnegative additive
clauses. -/
structure XOSBundleValuation
    {G : Type*} [DecidableEq G] (M : Finset G)
    extends BundleValuation M where
  /-- Existence of a finite nonempty XOS representation. -/
  isXOS :
    ∃ clauseCount : ℕ, 0 < clauseCount ∧
      ∃ clauseWeight : Fin clauseCount → BundlePriceVector M,
        (∀ c g, 0 ≤ clauseWeight c g) ∧
          ∀ S : BundleAllocation M,
            ∃ c : Fin clauseCount,
              val S =
                  S.1.attach.sum
                    (fun g => clauseWeight c ⟨g.1, S.2 g.2⟩) ∧
                ∀ d : Fin clauseCount,
                  S.1.attach.sum
                      (fun g => clauseWeight d ⟨g.1, S.2 g.2⟩) ≤
                    val S

/-- The measurable structure generated by the finitely many bundle-value coordinates. This
is the natural finite-dimensional Borel structure and, in particular, supports
ordinary continuous as well as discrete valuation priors. -/
instance instMeasurableSpaceSubadditiveBundleValuation
    {G : Type*} [DecidableEq G] {M : Finset G} :
    MeasurableSpace (SubadditiveBundleValuation M) :=
  MeasurableSpace.comap
    (fun v : SubadditiveBundleValuation M =>
      (v.val : BundleAllocation M → ℝ))
    inferInstance

instance instMeasurableSpaceXOSBundleValuation
    {G : Type*} [DecidableEq G] {M : Finset G} :
    MeasurableSpace (XOSBundleValuation M) :=
  MeasurableSpace.comap
    (fun v : XOSBundleValuation M =>
      (v.val : BundleAllocation M → ℝ))
    inferInstance

/-!
## Shared allocation and welfare vocabulary
-/

/-- A disjoint bundle allocation exhausts the ground set. -/
def IsCompleteBundleAllocation
    {I G : Type*} [DecidableEq G] {M : Finset G}
    (A : BundlePartitionAllocation I M) : Prop :=
  ∀ g ∈ M, ∃ i : I, g ∈ (A.1 i).1

/-- Native social welfare, specialized to arbitrary private bundle values. -/
noncomputable def bundleSocialWelfare
    {I G : Type*} [Fintype I] [DecidableEq G] {M : Finset G}
    (v : I → BundleAllocation M → ℝ)
    (A : BundlePartitionAllocation I M) : ℝ :=
  MultipleParameterMechanism.socialWelfare (fun i allocation => v i (allocation.1 i)) A

/-- Offline optimal welfare over all disjoint (possibly partial) allocations. -/
noncomputable def bundleOPT
    {I G : Type*} [Fintype I] [DecidableEq G] {M : Finset G}
    (v : I → BundleAllocation M → ℝ) : ℝ :=
  ⨆ A : BundlePartitionAllocation I M, bundleSocialWelfare v A

/-!
## Posted prices and demand choices
-/

/-- Quasi-linear utility of a bundle for an arbitrary value function. -/
def netBundleUtility
    {G : Type*} [DecidableEq G] {M : Finset G}
    (v : BundleAllocation M → ℝ) (p : BundlePriceVector M)
    (S : BundleAllocation M) : ℝ :=
  v S - S.1.attach.sum (fun g => p ⟨g.1, S.2 g.2⟩)

/-- A bundle maximizes quasi-linear utility among the bundles contained in the currently
available item set. -/
def IsDemandBundle
    {G : Type*} [DecidableEq G] {M : Finset G}
    (v : BundleAllocation M → ℝ) (p : BundlePriceVector M)
    (available : Finset G) (S : BundleAllocation M) : Prop :=
  S.1 ⊆ available ∧
    ∀ T : BundleAllocation M, T.1 ⊆ available →
      netBundleUtility v p T ≤ netBundleUtility v p S

/-!
## Partial fair allocations, approximation, and charity
-/

/-- Pairwise disjoint bundles contained in `allGoods`. The ambient goods type need not be
finite, and agent equality need not be decidable. -/
structure IsPartialIndivisibleAllocation
    {N G : Type*} [DecidableEq G]
    (allGoods : Finset G)
    (A : SocialChoice.FairDivision.Indivisible.Allocation N G) : Prop where
  /-- Allocated bundles are pairwise disjoint. -/
  disjoint : ∀ i j : N, i ≠ j → Disjoint (A i) (A j)
  /-- Every allocated good belongs to the instance. -/
  subset_goods : ∀ i : N, A i ⊆ allGoods

/-- Goods left unallocated by a partial allocation. -/
def charity
    {N G : Type*} [Fintype N] [DecidableEq G]
    (allGoods : Finset G)
    (A : SocialChoice.FairDivision.Indivisible.Allocation N G) : Finset G :=
  allGoods \ Finset.univ.biUnion A

/-- All-goods alpha-EFX, including zero-valued goods (also called EFX-zero). For goods the
usual factor range is [0,1]; each problem supplies its own normalization, monotonicity
and factor assumptions. -/
def IsAlphaEFXGoods
    {N G : Type*} [DecidableEq G]
    (α : ℝ) (v : SocialChoice.FairDivision.Indivisible.Valuation N G)
    (A : SocialChoice.FairDivision.Indivisible.Allocation N G) : Prop :=
  ∀ i j : N, i ≠ j → ∀ g ∈ A j,
    α * v.val i (A j \ {g}) ≤ v.val i (A i)

/-- At factor one, the approximate all-goods convention is exactly the native EFX
predicate, without extra valuation or allocation assumptions. -/
theorem isAlphaEFXGoods_one_iff
    {N G : Type*} [DecidableEq G]
    (v : SocialChoice.FairDivision.Indivisible.Valuation N G)
    (A : SocialChoice.FairDivision.Indivisible.Allocation N G) :
    IsAlphaEFXGoods 1 v A ↔ SocialChoice.FairDivision.Indivisible.IsEFX v A := by
  simp only [IsAlphaEFXGoods, one_mul, SocialChoice.FairDivision.Indivisible.IsEFX]

/-- Explicit name for the all-goods convention; identical to IsAlphaEFXGoods. -/
abbrev IsAlphaEFX0Goods
    {N G : Type*} [DecidableEq G]
    (α : ℝ) (v : SocialChoice.FairDivision.Indivisible.Valuation N G)
    (A : SocialChoice.FairDivision.Indivisible.Allocation N G) : Prop :=
  IsAlphaEFXGoods α v A

/-- The positive-marginal variant. For additive valuations the marginal condition equals
positive singleton value; this substitution is invalid for general valuations. -/
def IsAlphaEFXPositiveMarginalGoods
    {N G : Type*} [DecidableEq G]
    (α : ℝ) (v : SocialChoice.FairDivision.Indivisible.Valuation N G)
    (A : SocialChoice.FairDivision.Indivisible.Allocation N G) : Prop :=
  ∀ i j : N, i ≠ j → ∀ g ∈ A j,
    v.val i (A j \ {g}) < v.val i (A j) →
      α * v.val i (A j \ {g}) ≤ v.val i (A i)

/-- Every agent values its allocated bundle at least as highly as the unallocated goods. -/
def NoEnvyOfCharity
    {N G : Type*} [Fintype N] [DecidableEq G]
    (allGoods : Finset G)
    (v : SocialChoice.FairDivision.Indivisible.Valuation N G)
    (A : SocialChoice.FairDivision.Indivisible.Allocation N G) : Prop :=
  ∀ i : N, v.val i (charity allGoods A) ≤ v.val i (A i)

/-- Standard `α`-EFX for chores, using approximation factors `α ≥ 1`: deleting any chore
from the envious agent's own bundle leaves cost at most `α` times the other agent's
cost. Thus `α = 1` is exact EFX and larger values are weaker guarantees. -/
def IsAlphaEFXChores
    {N G : Type*} [DecidableEq G]
    (α : ℝ) (cost : SocialChoice.FairDivision.Indivisible.Valuation N G)
    (A : SocialChoice.FairDivision.Indivisible.Allocation N G) : Prop :=
  ∀ i j : N, i ≠ j → ∀ g ∈ A i,
    cost.val i (A i \ {g}) ≤ α * cost.val i (A j)

end EconCSLib.OpenProblem.New.EconCSBench
